<a href="https://colab.research.google.com/github/Preet-tech07/python-/blob/main/Pandas_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Yesterday, we learnt a little about the very useful library Pandas widely used for Data Analysis. It is time to put the many utilities of this library in front of our eyes. We will be performing following manipulations and exploration of our data:**

* ### Indexing and slicing operations
* ### Manipulating columns
* ### Exploring unique and missing values

In [ ]:
# Import pandas package
import pandas as pd
import numpy as np

In [ ]:
# loading csv File
file_path = '/content/drive/MyDrive/Colab Notebooks/Data Set/imdb_data.csv'
df=pd.read_csv(file_path)

In [ ]:
df.head()

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,release_date,runtime,spoken_languages,status,tagline,title,Keywords,cast,crew,revenue
0,1,"[{'id': 313576, 'name': 'Hot Tub Time Machine ...",14000000,"[{'id': 35, 'name': 'Comedy'}]",NaN,tt2637294,en,Hot Tub Time Machine 2,"When Lou, who has become the ""father of the In...",6.575393,...,2/20/15,93.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The Laws of Space and Time are About to be Vio...,Hot Tub Time Machine 2,"[{'id': 4379, 'name': 'time travel'}, {'id': 9...","[{'cast_id': 4, 'character': 'Lou', 'credit_id...","[{'credit_id': '59ac067c92514107af02c8c8', 'de...",12314651
1,2,"[{'id': 107674, 'name': 'The Princess Diaries ...",40000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,tt0368933,en,The Princess Diaries 2: Royal Engagement,Mia Thermopolis is now a college graduate and ...,8.248895,...,8/6/04,113.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,It can take a lifetime to find true love; she'...,The Princess Diaries 2: Royal Engagement,"[{'id': 2505, 'name': 'coronation'}, {'id': 42...","[{'cast_id': 1, 'character': 'Mia Thermopolis'...","[{'credit_id': '52fe43fe9251416c7502563d', 'de...",95149435
2,3,NaN,3300000,"[{'id': 18, 'name': 'Drama'}]",http://sonyclassics.com/whiplash/,tt2582802,en,Whiplash,"Under the direction of a ruthless instructor, ...",64.299990,...,10/10/14,105.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The road to greatness can take you to the edge.,Whiplash,"[{'id': 1416, 'name': 'jazz'}, {'id': 1523, 'n...","[{'cast_id': 5, 'character': 'Andrew Neimann',...","[{'credit_id': '54d5356ec3a3683ba0000039', 'de...",13092000
3,4,NaN,1200000,"[{'id': 53, 'name': 'Thriller'}, {'id': 18, 'n...",http://kahaanithefilm.com/,tt1821480,hi,Kahaani,Vidya Bagchi (Vidya Balan) arrives in Kolkata ...,3.174936,...,3/9/12,122.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,NaN,Kahaani,"[{'id': 10092, 'name': 'mystery'}, {'id': 1054...","[{'cast_id': 1, 'character': 'Vidya Bagchi', '...","[{'credit_id': '52fe48779251416c9108d6eb', 'de...",16000000
4,5,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",NaN,tt1380152,ko,마린보이,Marine Boy is the story of a former national s...,1.148070,...,2/5/09,118.0,"[{'iso_639_1': 'ko', 'name': '한국어/조선말'}]",Released,NaN,Marine Boy,NaN,"[{'cast_id': 3, 'character': 'Chun-soo', 'cred...","[{'credit_id': '52fe464b9251416c75073b43', 'de...",3923970

# <u>**<code>describe()</code>**</u>

## This method gives the overall descriptive summary of the dataframe. This works only for numerical columns

In [ ]:
df.describe()

                id        budget   popularity      runtime       revenue
count  3000.000000  3.000000e+03  3000.000000  2998.000000  3.000000e+03
mean   1500.500000  2.253133e+07     8.463274   107.856571  6.672585e+07
std     866.169729  3.702609e+07    12.104000    22.086434  1.375323e+08
min       1.000000  0.000000e+00     0.000001     0.000000  1.000000e+00
25%     750.750000  0.000000e+00     4.018053    94.000000  2.379808e+06
50%    1500.500000  8.000000e+06     7.374861   104.000000  1.680707e+07
75%    2250.250000  2.900000e+07    10.890983   118.000000  6.891920e+07
max    3000.000000  3.800000e+08   294.337037   338.000000  1.519558e+09

In [ ]:
3.000000e+03

3000.0

# <u>**Indexing and Slicing**</u>

In [ ]:
df.head()

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,release_date,runtime,spoken_languages,status,tagline,title,Keywords,cast,crew,revenue
0,1,"[{'id': 313576, 'name': 'Hot Tub Time Machine ...",14000000,"[{'id': 35, 'name': 'Comedy'}]",NaN,tt2637294,en,Hot Tub Time Machine 2,"When Lou, who has become the ""father of the In...",6.575393,...,2/20/15,93.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The Laws of Space and Time are About to be Vio...,Hot Tub Time Machine 2,"[{'id': 4379, 'name': 'time travel'}, {'id': 9...","[{'cast_id': 4, 'character': 'Lou', 'credit_id...","[{'credit_id': '59ac067c92514107af02c8c8', 'de...",12314651
1,2,"[{'id': 107674, 'name': 'The Princess Diaries ...",40000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,tt0368933,en,The Princess Diaries 2: Royal Engagement,Mia Thermopolis is now a college graduate and ...,8.248895,...,8/6/04,113.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,It can take a lifetime to find true love; she'...,The Princess Diaries 2: Royal Engagement,"[{'id': 2505, 'name': 'coronation'}, {'id': 42...","[{'cast_id': 1, 'character': 'Mia Thermopolis'...","[{'credit_id': '52fe43fe9251416c7502563d', 'de...",95149435
2,3,NaN,3300000,"[{'id': 18, 'name': 'Drama'}]",http://sonyclassics.com/whiplash/,tt2582802,en,Whiplash,"Under the direction of a ruthless instructor, ...",64.299990,...,10/10/14,105.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The road to greatness can take you to the edge.,Whiplash,"[{'id': 1416, 'name': 'jazz'}, {'id': 1523, 'n...","[{'cast_id': 5, 'character': 'Andrew Neimann',...","[{'credit_id': '54d5356ec3a3683ba0000039', 'de...",13092000
3,4,NaN,1200000,"[{'id': 53, 'name': 'Thriller'}, {'id': 18, 'n...",http://kahaanithefilm.com/,tt1821480,hi,Kahaani,Vidya Bagchi (Vidya Balan) arrives in Kolkata ...,3.174936,...,3/9/12,122.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,NaN,Kahaani,"[{'id': 10092, 'name': 'mystery'}, {'id': 1054...","[{'cast_id': 1, 'character': 'Vidya Bagchi', '...","[{'credit_id': '52fe48779251416c9108d6eb', 'de...",16000000
4,5,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",NaN,tt1380152,ko,마린보이,Marine Boy is the story of a former national s...,1.148070,...,2/5/09,118.0,"[{'iso_639_1': 'ko', 'name': '한국어/조선말'}]",Released,NaN,Marine Boy,NaN,"[{'cast_id': 3, 'character': 'Chun-soo', 'cred...","[{'credit_id': '52fe464b9251416c75073b43', 'de...",3923970

## **<code>iloc</code>** gets rows (or columns) at particular positions in the index (so it only takes integers).

In [ ]:
#df.iloc[rows,columns]

In [ ]:
df.iloc[:5,1:3]

                               belongs_to_collection    budget
0  [{'id': 313576, 'name': 'Hot Tub Time Machine ...  14000000
1  [{'id': 107674, 'name': 'The Princess Diaries ...  40000000
2                                                NaN   3300000
3                                                NaN   1200000
4                                                NaN         0

## **<code>loc</code>** gets rows (or columns) with particular labels from the index.

In [ ]:
#df.loc[rows,[columns_name]]

In [ ]:
df.loc[:5,['title','runtime','belongs_to_collection']]

,title,runtime,belongs_to_collection
0,Hot Tub Time Machine 2,93.0,"[{'id': 313576, 'name': 'Hot Tub Time Machine ..."
1,The Princess Diaries 2: Royal Engagement,113.0,"[{'id': 107674, 'name': 'The Princess Diaries ..."
2,Whiplash,105.0,NaN
3,Kahaani,122.0,NaN
4,Marine Boy,118.0,NaN
5,Pinocchio and the Emperor of the Night,83.0,NaN

In [ ]:
df.loc[:,['title','runtime']]

                                         title  runtime
0                       Hot Tub Time Machine 2     93.0
1     The Princess Diaries 2: Royal Engagement    113.0
2                                     Whiplash    105.0
3                                      Kahaani    122.0
4                                   Marine Boy    118.0
...                                        ...      ...
2995                                   Chasers    102.0
2996                          We Are the Best!    102.0
2997                   The Long Kiss Goodnight    120.0
2998                          Along Came Polly     90.0
2999                                 Abduction    106.0

[3000 rows x 2 columns]

In [ ]:
df[['title','runtime']]

                                         title  runtime
0                       Hot Tub Time Machine 2     93.0
1     The Princess Diaries 2: Royal Engagement    113.0
2                                     Whiplash    105.0
3                                      Kahaani    122.0
4                                   Marine Boy    118.0
...                                        ...      ...
2995                                   Chasers    102.0
2996                          We Are the Best!    102.0
2997                   The Long Kiss Goodnight    120.0
2998                          Along Came Polly     90.0
2999                                 Abduction    106.0

[3000 rows x 2 columns]

In [ ]:
df.head()

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,release_date,runtime,spoken_languages,status,tagline,title,Keywords,cast,crew,revenue
0,1,"[{'id': 313576, 'name': 'Hot Tub Time Machine ...",14000000,"[{'id': 35, 'name': 'Comedy'}]",NaN,tt2637294,en,Hot Tub Time Machine 2,"When Lou, who has become the ""father of the In...",6.575393,...,2/20/15,93.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The Laws of Space and Time are About to be Vio...,Hot Tub Time Machine 2,"[{'id': 4379, 'name': 'time travel'}, {'id': 9...","[{'cast_id': 4, 'character': 'Lou', 'credit_id...","[{'credit_id': '59ac067c92514107af02c8c8', 'de...",12314651
1,2,"[{'id': 107674, 'name': 'The Princess Diaries ...",40000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,tt0368933,en,The Princess Diaries 2: Royal Engagement,Mia Thermopolis is now a college graduate and ...,8.248895,...,8/6/04,113.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,It can take a lifetime to find true love; she'...,The Princess Diaries 2: Royal Engagement,"[{'id': 2505, 'name': 'coronation'}, {'id': 42...","[{'cast_id': 1, 'character': 'Mia Thermopolis'...","[{'credit_id': '52fe43fe9251416c7502563d', 'de...",95149435
2,3,NaN,3300000,"[{'id': 18, 'name': 'Drama'}]",http://sonyclassics.com/whiplash/,tt2582802,en,Whiplash,"Under the direction of a ruthless instructor, ...",64.299990,...,10/10/14,105.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The road to greatness can take you to the edge.,Whiplash,"[{'id': 1416, 'name': 'jazz'}, {'id': 1523, 'n...","[{'cast_id': 5, 'character': 'Andrew Neimann',...","[{'credit_id': '54d5356ec3a3683ba0000039', 'de...",13092000
3,4,NaN,1200000,"[{'id': 53, 'name': 'Thriller'}, {'id': 18, 'n...",http://kahaanithefilm.com/,tt1821480,hi,Kahaani,Vidya Bagchi (Vidya Balan) arrives in Kolkata ...,3.174936,...,3/9/12,122.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,NaN,Kahaani,"[{'id': 10092, 'name': 'mystery'}, {'id': 1054...","[{'cast_id': 1, 'character': 'Vidya Bagchi', '...","[{'credit_id': '52fe48779251416c9108d6eb', 'de...",16000000
4,5,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",NaN,tt1380152,ko,마린보이,Marine Boy is the story of a former national s...,1.148070,...,2/5/09,118.0,"[{'iso_639_1': 'ko', 'name': '한국어/조선말'}]",Released,NaN,Marine Boy,NaN,"[{'cast_id': 3, 'character': 'Chun-soo', 'cred...","[{'credit_id': '52fe464b9251416c75073b43', 'de...",3923970

In [ ]:
df[df['original_language'] == 'hi']

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,release_date,runtime,spoken_languages,status,tagline,title,Keywords,cast,crew,revenue
3,4,NaN,1200000,"[{'id': 53, 'name': 'Thriller'}, {'id': 18, 'n...",http://kahaanithefilm.com/,tt1821480,hi,Kahaani,Vidya Bagchi (Vidya Balan) arrives in Kolkata ...,3.174936,...,3/9/12,122.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,NaN,Kahaani,"[{'id': 10092, 'name': 'mystery'}, {'id': 1054...","[{'cast_id': 1, 'character': 'Vidya Bagchi', '...","[{'credit_id': '52fe48779251416c9108d6eb', 'de...",16000000
213,214,NaN,6700000,"[{'id': 28, 'name': 'Action'}]",NaN,tt2077833,hi,राउडी राठौर,Low-life thief Shiva and top-cop Vikram Rathor...,1.312833,...,6/1/12,143.0,"[{'iso_639_1': 'hi', 'name': 'हिन्दी'}]",Released,NaN,Rowdy Rathore,"[{'id': 1721, 'name': 'fight'}, {'id': 8015, '...","[{'cast_id': 11, 'character': 'Shiva / Vikram ...","[{'credit_id': '52fe4a0bc3a36847f81b58a9', 'de...",31000000
371,372,NaN,13100000,"[{'id': 18, 'name': 'Drama'}, {'id': 35, 'name...",http://www.thankyouthefilm.com/,tt1720254,hi,Thank You,The film is about three husbands having affair...,1.417392,...,4/8/11,140.0,"[{'iso_639_1': 'hi', 'name': 'हिन्दी'}]",Released,Husbands will say sorry ... Wives will say tha...,Thank You,NaN,"[{'cast_id': 1, 'character': 'Kishen', 'credit...","[{'credit_id': '52fe4651c3a368484e08a13f', 'de...",4100000
401,402,NaN,3000000,"[{'id': 18, 'name': 'Drama'}, {'id': 36, 'name...",NaN,tt0319736,hi,The Legend of Bhagat Singh,The Legend of Bhagat Singh is a 2002 Indian hi...,0.904409,...,6/7/02,155.0,"[{'iso_639_1': 'pa', 'name': 'ਪੰਜਾਬੀ'}, {'iso_...",Released,NaN,The Legend of Bhagat Singh,NaN,"[{'cast_id': 12, 'character': 'Bhagat K. Singh...","[{'credit_id': '52fe44849251416c9101372f', 'de...",6000000
419,420,NaN,3750000,"[{'id': 35, 'name': 'Comedy'}, {'id': 10769, '...",http://www.atithithefilm.com/,tt1578116,hi,Atithi Tum Kab Jaoge,Atithi Tum Kab Jaoge? is the story of Puneet a...,0.597058,...,2/26/10,155.0,"[{'iso_639_1': 'hi', 'name': 'हिन्दी'}]",Released,NaN,"Dear Guest, When Will You Leave?",NaN,"[{'cast_id': 1, 'character': 'Puneet, Pappu', ...","[{'credit_id': '5647c0359251413ade004b4d', 'de...",5000000
481,482,NaN,10500000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",http://www.cc2c-thefilm.com/,tt1091229,hi,Chandni Chowk To China,"Based in Delhi's Chandni Chowk, orphaned Sidhu...",1.970481,...,1/16/09,149.0,"[{'iso_639_1': 'de', 'name': 'Deutsch'}, {'iso...",Released,NaN,Chandni Chowk To China,"[{'id': 4344, 'name': 'musical'}, {'id': 10540...","[{'cast_id': 10, 'character': 'Sidhu', 'credit...","[{'credit_id': '52fe43d2c3a368484e00004d', 'de...",9400000
585,586,NaN,10400000,"[{'id': 18, 'name': 'Drama'}]",NaN,tt5074352,hi,दंगल,Dangal is an extraordinary true story based on...,8.792104,...,12/23/16,161.0,"[{'iso_639_1': 'hi', 'name': 'हिन्दी'}]",Released,NaN,Dangal,"[{'id': 5565, 'name': 'biography'}, {'id': 597...","[{'cast_id': 0, 'character': 'Mahavir Singh Ph...","[{'credit_id': '5714ef3f92514146c80003ea', 'de...",310000000
627,628,NaN,16000000,"[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",http://www.yashrajfilms.com/Movies/MovieIndivi...,tt3495026,hi,Fan,The story of a fan whose world completely revo...,5.127876,...,4/15/16,142.0,"[{'iso_639_1': 'hi', 'name': 'हिन्दी'}]",Released,World's biggest superstar got the universe's b...,Fan,"[{'id': 1523, 'name': 'obsession'}, {'id': 981...","[{'cast_id': 1, 'character': 'Gaurav Chandna /...","[{'credit_id': '569bc0de9251415e7000003c', 'de...",29251596
671,672,NaN,6400000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",http://www.anjaanaanjaani.erosentertainment.com,tt1499201,hi,Anjaana Anjaani,Akash (Ranbir Kapoor) and Kiara (Priyanka Chop...,1.822940,...,9/24/10,151.0,"[{'iso_639_1': 'hi', 'name': 'हिन्दी'}]",Released,All the greatest love stories...are between st...,Anjaana Anjaani,"[{'id': 1252, 'name': 'suicide attempt'}, {'id...","[{'cast_id': 2, 'character': 'Kiara', 'credit_...","[{'credit_id': '58a2fb2cc3a3682902007108', 'de...",5900000
695,696,NaN,1,"[{'id': 10749, 'name': 'Romance'}, {'id': 53, ...",NaN,tt0374271,hi,Tere Naam,"Lower Caste Radhey Mohan is a no good slacker,...",1.280455,...,8/15/03,132.0,"[{'iso_639_1': 'hi', 'name': 'हिन्दी'}]",Released,Unfortunately a true love story,Tere Naam,NaN,"[{'cast_id': 3, 'character': 'Radhe Mohan', 'c...","[{'credit_id': '52fe491ec3a36847f8189cfb', 'de...",2
771,772,NaN,9000000,"[{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...",http://kaminey.utvnet.com/,tt1274295,hi,Kaminey,Guddu and Charlie are identical twins born and...,2.089842,...,8/14/09,135.0,"[{'iso_639_1': 'de', 'name': 'Deutsch'}]",Released,Thif monfoon. Difcover your mean fide.,Kaminey,"[{'id': 14636, 'name': 'india'}]","[{'cast_id': 1, 'character': 'Charlie / Guddu'...","[{'credit_id': '52fe43f4c3a368484e007b65', 'de...",18130000
840,841,NaN,10721568,"[{'id': 18, 'name': 'Drama'}]",https://www.facebook.com/foxstarhindi/,tt5286444,hi,नीरजा,Neerja is a portrayal on the life of the coura...,1.686250,...,2/19/16,122.0,"[{'iso_639_1': 'hi', 'name': 'हिन्दी'}]",Released,Fear Gave Her Courage,Neerja,"[{'id': 4245, 'name': 'hijacking'}, {'id': 967...","[{'cast_id': 0, 'character': 'Neerja Bhanot', ...","[{'credit_id': '5692588192514115bf001d11', 'de...",2978994
848,849,NaN,6400000,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",NaN,tt2359810,hi,रान्झाना,A small-town boy needs to break through the cl...,1.856101,...,6/21/13,140.0,"[{'iso_639_1': 'hi', 'name': 'हिन्दी'}]",Released,NaN,Raanjhanaa,"[{'id': 10048, 'name': 'unrequited love'}, {'i...","[{'cast_id': 1, 'character': 'Kundan', 'credit...","[{'credit_id': '52fe4c799251416c910f611d', 'de...",18000000
970,971,NaN,4200000,"[{'id': 10749, 'name': 'Romance'}, {'id': 28, ...",NaN,tt3142232,hi,Heropanti,Rising from present India in the conflicting e...,2.031919,...,5/23/14,146.0,"[{'iso_639_1': 'hi', 'name': 'हिन्दी'}]",Released,NaN,Heropanti,NaN,"[{'cast_id': 1, 'character': 'Bablu', 'credit_...","[{'credit_id': '53baa148c3a3685eb4006e29', 'de...",10000000
1004,1005,NaN,1000000,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",NaN,tt2350496,hi,Dabba,A mistaken delivery in Mumbai's famously effic...,10.766409,...,9/19/13,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,NaN,The Lunchbox,NaN,"[{'cast_id': 2, 'character': 'Saajan Fernandes...","[{'credit_id': '5476f65b9251415d7a0016eb', 'de...",4235151
1491,1492,NaN,5500000,"[{'id': 18, 'name': 'Drama'}, {'id': 35, 'name...",NaN,tt3767372,hi,Piku,"A road trip to Kolkata brings Piku, an archite...",2.942711,...,5/8/15,123.0,"[{'iso_639_1': 'hi', 'name': 'हिन्दी'}]",Released,Motion Se Hi Emotion,Piku,NaN,"[{'cast_id': 0, 'character': 'Bashkor Banerjee...","[{'credit_id': '5551de509251416a93005e01', 'de...",22159216
1572,1573,NaN,9100000,"[{'id': 53, 'name': 'Thriller'}, {'id': 28, 'n...",http://www.rememberghajini.com/,tt1166100,hi,Ghajini,Sanjay a rich tycoon suffering from short term...,4.239080,...,12/25/08,183.0,"[{'iso_639_1': 'hi', 'name': 'हिन्दी'}]",Released,NaN,Ghajini,"[{'id': 331, 'name': 'tattoo'}, {'id': 154785,...","[{'cast_id': 12, 'character': 'Sanjay Singhani...","[{'credit_id': '52fe45c99251416c75062659', 'de...",76000000
1640,1641,NaN,4600000,"[{'id': 36, 'name': 'History'}, {'id': 28, 'na...",NaN,tt2356180,hi,Bhaag Milkha Bhaag,"The true story of the ""Flying Sikh"" world cham...",4.342418,...,7/12/13,186.0,"[{'iso_639_1': 'hi', 'name': 'हिन्दी'}]",Released,Now you will see his Real Story.,Bhaag Milkha Bhaag,"[{'id': 795, 'name': 'running'}, {'id': 1721, ...","[{'cast_id': 1, 'character': 'Milkha Singh', '...","[{'credit_id': '52fe4d1ac3a368484e1d74af', 'de...",25000000
1656,1657,NaN,18000000,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",http://www.chennaiexp2013.com/chennaiexpress.aspx,tt2112124,hi,Chennai Express,Rahul embarks on a journey to a small town in ...,4.193560,...,8/9/13,141.0,"[{'iso_639_1': 'hi', 'name': 'हिन्दी'}, {'iso_...",Released,Ready... Steady... Po!,Chennai Express,"[{'id': 4412, 'name': 'grandfather'}, {'id': 4...","[{'cast_id': 2, 'character': 'Rahul Mithaiwala...","[{'credit_id': '581e56659251410f4f00f125', 'de...",62000000
1694,1695,NaN,521873,"[{'id': 53, 'name': 'Thriller'}, {'id': 80, 'n...",NaN,tt5662932,hi,रमन राघव २.०,Set in present day Mumbai the story follows th...,1.668794,...,6/24/16,127.0,"[{'iso_639_1': 'hi', 'name': 'हिन्दी'}]",Released,NaN,Raman Raghav 2.0,"[{'id': 10024, 'name': 'psychopathic killer'},...","[{'cast_id': 6, 'character': 'Ramanna (Raman)'...","[{'credit_id': '57160f17c3a3682f450033eb', 'de...",1013926
1719,1720,NaN,4437508,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",http://www.utvgroup.com/motion-pictures/coming...,tt2082197,hi,Barfi!,He is cute. He's shrewd. The girls love him. T...,3.779077,...,9/14/12,155.0,"[{'iso_639_1': 'hi', 'name': 'हिन्दी'}]",Released,NaN,Barfi,"[{'id': 1646, 'name': 'autism'}]","[{'cast_id': 5, 'character': 'Jhilmil Singh', ...","[{'credit_id': '5926294cc3a36877fd014ce9', 'de...",2804874
1729,1730,NaN,5200000,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",NaN,tt0164538,hi,दिल से,The clash between love and ideology is portray...,1.891138,...,8/22/98,163.0,"[{'iso_639_1': 'hi', 'name': 'हिन्दी'}, {'iso_...",Released,NaN,Dil Se..,"[{'id': 258, 'name': 'bomb'}, {'id': 321, 'nam...","[{'cast_id': 2, 'character': 'Amarkanth Varma'...","[{'credit_id': '57b53e789251410918000155', 'de...",13000000
1732,1733,"[{'id': 419784, 'name': 'Masti Collection', 'p...",5500000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,tt2476154,hi,Grand Masti,"Amar, Prem and Meet are longtime friends who h...",1.250293,...,9/13/13,140.0,"[{'iso_639_1': 'hi', 'name': 'हिन्दी'}]",Released,The Masti Boys are Back,Grand Masti,NaN,"[{'cast_id': 2, 'character': 'Amar', 'credit_i...","[{'credit_id': '52fe4db49251416c7513dd27', 'de...",47000000
1766,1767,NaN,0,"[{'id': 10749, 'name': 'Romance'}, {'id': 18, ...",NaN,tt0290326,hi,Tum Bin,"Shekhar, a businessman, accidentally kills his...",0.371679,...,7/13/01,158.0,"[{'iso_639_1': 'hi', 'name': 'हिन्दी'}]",Released,Love Will Find the Way,Tum Bin,"[{'id': 128, 'name': 'love triangle'}, {'id': ...","[{'cast_id': 1, 'character': 'Shekhar Malhotra...","[{'credit_id': '52fe46efc3a368484e0abfaf', 'de...",1486992
1948,1949,NaN,0,"[{'id': 35, 'name': 'Comedy'}, {'id': 80, 'nam...",NaN,tt0476805,hi,मालामाल वीकली,Lilaram sells lottery tickets and one customer...,1.479018,...,3/10/06,138.0,"[{'iso_639_1': 'hi', 'name': 'हिन्दी'}]",Released,NaN,Malamaal Weekly,NaN,"[{'cast_id': 1, 'character': 'Kanhaiya', 'cred...","[{'credit_id': '592dd1fbc3a36808c3000dd9', 'de...",204
1987,1988,NaN,0,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,tt0347304,hi,कल हो ना हो,Naina is a very serious girl with a very serio...,5.584308,...,11/27/03,186.0,"[{'iso_639_1': 'de', 'name': 'Deutsch'}, {'iso...",Released,NaN,Kal Ho Naa Ho,"[{'id': 242, 'name': 'new york'}, {'id': 958, ...","[{'cast_id': 8, 'character': 'Aman Mathur', 'c...","[{'credit_id': '52fe43b6c3a36847f8069c57', 'de...",13200241
1989,1990,"[{'id': 20970, 'name': 'Sarkar Collection', 'p...",1900000,"[{'id': 80, 'name': 'Crime'}, {'id': 28, 'name...",NaN,tt0432047,hi,Sarkar,"The authority of a man, who runs a parallel go...",2.004745,...,7/1/05,123.0,"[{'iso_639_1': 'hi', 'name': 'हिन्दी'}]",Released,NaN,Sarkar,"[{'id': 417, 'name': 'corruption'}, {'id': 607...","[{'cast_id': 1, 'character': 'Subhash Nagre (S...","[{'credit_id': '576bae81c3a36864910013fc', 'de...",5900000
2239,2240,"[{'id': 44976, 'name': 'Dhoom Series', 'poster...",19500000,"[{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...",NaN,tt1833673,hi,धूम ३,"To avenge his father's death, a circus enterta...",5.326716,...,12/18/13,172.0,"[{'iso_639_1': 'hi', 'name': 'हिन्दी'}]",Released,NaN,Dhoom 3,"[{'id': 291, 'name': 'circus'}, {'id': 2492, '...","[{'cast_id': 2, 'character': 'Sahir', 'credit_...","[{'credit_id': '59488707c3a36816c504b523', 'de...",91000000
2251,2252,NaN,130,"[{'id': 18, 'name': 'Drama'}, {'id': 28, 'name...",NaN,tt1729637,hi,Bodyguard,Lovely Singh (Salman Khan) is the bodyguard of...,2.402032,...,8/31/11,130.0,"[{'iso_639_1': 'hi', 'name': 'हिन्दी'}]",Released,NaN,Bodyguard,"[{'id': 2251, 'name': 'lie'}, {'id': 2913, 'na...","[{'cast_id': 1, 'character': 'Lovely B. Singh'...","[{'credit_id': '52fe48a1c3a368484e102d25', 'de...",8
2287,2288,NaN,18000000,"[{'id': 80, 'name': 'Crime'}, {'id': 18, 'name...",NaN,tt2979920,hi,बॉम्बे वेलवेट,"An ordinary man, who goes against all odds to ...",1.377993,...,5/15/15,151.0,"[{'iso_639_1': 'hi', 'name': 'हिन्दी'}]",Released,NaN,Bombay Velvet,"[{'id': 1416, 'name': 'jazz'}, {'id': 2792, 'n...","[{'cast_id': 1, 'character': 'Rosie', 'credit_...","[{'credit_id': '57d00957c3a36866a400269f', 'de...",1500000
2353,2354,NaN,8376800,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",http://www.jodhaaakbar.com/,tt0449994,hi,Jodhaa Akbar,Jodhaa Akbar is a sixteenth century love story...,12.237488,...,2/15/08,213.0,"[{'iso_639_1': 'hi', 'name': 'हिन्दी'}, {'iso_...",Released,NaN,Jodhaa Akbar,"[{'id': 1157, 'name': 'wife husband relationsh...","[{'cast_id': 1, 'character': 'Jalaluddin Moham...","[{'credit_id': '52fe45c99251416c75062761', 'de...",13000000
2390,2391,NaN,7500000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",http://www.khattameethathefilm.com/,tt1455811,hi,Khatta Meetha,"Struggling road construction contractor, Sachi...",0.494047,...,7/23/10,155.0,"[{'iso_639_1': 'hi', 'name': 'हिन्दी'}]",Released,NaN,Khatta Meetha,"[{'id': 235064, 'name': 'remake of malayalam f...","[{'cast_id': 4, 'character': 'Sachin Tichkule'...","[{'credit_id': '52fe468fc3a36847f8105a21', 'de...",10000000
2436,2437,NaN,4300000,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",NaN,tt5946128,hi,Dear Zindagi,An unconventional thinker (Shah Rukh Khan) hel...,3.699552,...,11/24/16,149.0,"[{'iso_639_1': 'hi', 'name': 'हिन्दी'}]",Released,NaN,Dear Zindagi,NaN,"[{'cast_id': 8, 'character': 'Kaira', 'credit_...","[{'credit_id': '57c6e9c3c3a3680ba4001c63', 'de...",3376375
2480,2481,NaN,6400000,"[{'id': 10749, 'name': 'Romance'}, {'id': 18, ...",NaN,tt2168910,hi,Cocktail,"Gautam is an incorrigible flirt, who runs afte...",7.950488,...,7/13/12,144.0,"[{'iso_639_1': 'hi', 'name': 'हिन्दी'}]",Released,Sometimes good friends may be too good to shar...,Cocktail,"[{'id': 6054, 'name': 'friendship'}, {'id': 97...","[{'cast_id': 7, 'character': 'Veronica Malaney...","[{'credit_id': '52fe4bc8c3a36847f8213af9', 'de...",18800000
2538,2539,NaN,6900000,"[{'id': 10749, 'name': 'Romance'}, {'id': 18, ...",NaN,tt0151150,hi,Josh,Shah Rukh Khan and Sharad Kapoor are the leade...,4.031500,...,6/9/00,162.0,"[{'iso_639_1': 'de', 'name': 'Deutsch'}, {'iso...",Released,NaN,Josh,NaN,"[{'cast_id': 1, 'character': 'Max', 'credit_id...","[{'credit_id': '52fe4b82c3a368484e18c7f1', 'de...",15000000
2563,2564,NaN,7400000,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",NaN,tt0449999,hi,कभी अलविदा ना कहना,Dev and Maya are both married to different peo...,2.372520,...,8/11/06,193.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,A Love.... That Broke All Relationships,Kabhi Alvida Naa Kehna,"[{'id': 596, 'name': 'adultery'}, {'id': 34094...","[{'cast_id': 1, 'character': 'Dev Saran', 'cre...","[{'credit_id': '52fe45ee9251416c75067637', 'de...",17000000
2567,2568,NaN,11000000,"[{'id': 18, 'name': 'Drama'}, {'id': 28, 'name...",NaN,tt2424988,hi,Gabbar Is Back,A vigilante network taking out corrupt officia...,1.812728,...,5/1/15,128.0,"[{'iso_639_1': 'hi', 'name': 'हिन्दी'}]",Released,NaN,Gabbar Is Back,NaN,"[{'cast_id': 1, 'character': 'Professor Aditya...","[{'credit_id': '5792ff149251410d12008917', 'de...",41000000
2807,2808,NaN,5300000,"[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",NaN,tt0439662,hi,Fanaa,Zooni Ali Beg (Kajol) is a blind Kashmiri girl...,3.003526,...,5/26/06,168.0,"[{'iso_639_1': 'hi', 'name': 'हिन्दी'}, {'iso_...",Released,Destroyed in love...,Fanaa,"[{'id': 1741, 'name': 'blindness and impaired ...","[{'cast_id': 4, 'character': 'Zooni Ali Beg', ...","[{'credit_id': '52fe44aac3a36847f80a3315', 'de...",22175908
2828,2829,NaN,19500000,"[{'id': 10752, 'name': 'War'}, {'id': 36, 'nam...",NaN,tt3735246,hi,Bajirao Mastani,A historical account of the romance between th...,4.683689,...,12/18/15,150.0,"[{'iso_639_1': 'de', 'name': 'Deutsch'}, {'iso...",Released,NaN,Bajirao Mastani,"[{'id': 232174, 'name': '–ª—é–±–æ–≤—å'}, {'id'...","[{'cast_id': 1, 'character': 'Baji Rao I', 'cr...","[{'credit_id': '560b66e0c3a3686814004c7d', 'de...",56000000
2857,2858,NaN,5400000,"[{'id': 53, 'name': 'Thriller'}]",NaN,tt2855648,hi,Madras Cafe,An Indian Intelligence agent journeys into a w...,2.399890,...,8/23/13,130.0,"[{'iso_639_1': 'hi', 'name': 'हिन्दी'}]",Released,Intercept the truth,Madras Cafe,"[{'id': 1990, 'name': 'cupboard'}, {'id': 5299...","[{'cast_id': 2, 'character': 'Vikram Singh', '...","[{'credit_id': '52fe4e08c3a368484e20a8ed', 'de...",6500000
2859,2860,"[{'id': 286951, 'name': 'Singham Collection', ...",3062000,"[{'id': 18, 'name': 'Drama'}, {'id': 28, 'name...",NaN,tt1948150,hi,Singham,A Bollywood classic directed by Rodit Shetty. ...,2.077410,...,7/22/11,143.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,NaN,Singham,"[{'id': 1721, 'name': 'fight'}, {'id': 13116, ...","[{'cast_id': 1, 'character': 'Bajirao Singham'...","[{'credit_id': '52fe4802c3a368484e0e513f', 'de...",25034000
2959,2960,NaN,2300000,"[{'id': 18, 'name': 'Drama'}, {'id': 35, 'name...",NaN,tt1093370,hi,Jab We Met,"Depressed after the passing of his father, Dha...",3.959411,...,10/26/07,145.0,"[{'iso_639_1': 'hi', 'name': 'हिन्दी'}, {'iso_...",Released,NaN,Jab We Met,"[{'id': 2038, 'name': ""love of one's life""}, {...","[{'cast_id': 9, 'character': 'Aditya Kashyap',...","[{'credit_id': '537ef0d8c3a36805a1002844', 'de...",4600000

In [ ]:
hindi_movies = df[df['original_language'] == 'hi'][['title','original_language','runtime']]
hindi_movies

                                 title original_language  runtime
3                              Kahaani                hi    122.0
213                      Rowdy Rathore                hi    143.0
371                          Thank You                hi    140.0
401         The Legend of Bhagat Singh                hi    155.0
419   Dear Guest, When Will You Leave?                hi    155.0
481             Chandni Chowk To China                hi    149.0
585                             Dangal                hi    161.0
627                                Fan                hi    142.0
671                    Anjaana Anjaani                hi    151.0
695                          Tere Naam                hi    132.0
771                            Kaminey                hi    135.0
840                             Neerja                hi    122.0
848                         Raanjhanaa                hi    140.0
970                          Heropanti                hi    146.0
1004                      The Lunchbox                hi    104.0
1491                              Piku                hi    123.0
1572                           Ghajini                hi    183.0
1640                Bhaag Milkha Bhaag                hi    186.0
1656                   Chennai Express                hi    141.0
1694                  Raman Raghav 2.0                hi    127.0
1719                             Barfi                hi    155.0
1729                          Dil Se..                hi    163.0
1732                       Grand Masti                hi    140.0
1766                           Tum Bin                hi    158.0
1948                   Malamaal Weekly                hi    138.0
1987                     Kal Ho Naa Ho                hi    186.0
1989                            Sarkar                hi    123.0
2239                           Dhoom 3                hi    172.0
2251                         Bodyguard                hi    130.0
2287                     Bombay Velvet                hi    151.0
2353                      Jodhaa Akbar                hi    213.0
2390                     Khatta Meetha                hi    155.0
2436                      Dear Zindagi                hi    149.0
2480                          Cocktail                hi    144.0
2538                              Josh                hi    162.0
2563            Kabhi Alvida Naa Kehna                hi    193.0
2567                    Gabbar Is Back                hi    128.0
2807                             Fanaa                hi    168.0
2828                   Bajirao Mastani                hi    150.0
2857                       Madras Cafe                hi    130.0
2859                           Singham                hi    143.0
2959                        Jab We Met                hi    145.0

In [ ]:
hindi_movies.shape

(42, 3)

In [ ]:
df[df['runtime'] >120][['title','original_language','runtime']]

                    title original_language  runtime
3                 Kahaani                hi    122.0
12        American Beauty                en    122.0
14        Minority Report                en    145.0
20          Lost in Space                en    130.0
33        ABCs of Death 2                en    125.0
...                   ...               ...      ...
2969         Gosford Park                en    137.0
2970        The Bodyguard                en    129.0
2980     Action Hero Biju                ml    144.0
2992  The Thief of Bagdad                en    149.0
2993         The Terminal                en    128.0

[657 rows x 3 columns]

# <u>**Next let us see how we can manipulate columns**</u>

In [ ]:
df['runtime'].head()

0     93.0
1    113.0
2    105.0
3    122.0
4    118.0
Name: runtime, dtype: float64

In [ ]:
df['half_runtime'] = df['runtime']/2
df.head()

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,runtime,spoken_languages,status,tagline,title,Keywords,cast,crew,revenue,half_runtime
0,1,"[{'id': 313576, 'name': 'Hot Tub Time Machine ...",14000000,"[{'id': 35, 'name': 'Comedy'}]",NaN,tt2637294,en,Hot Tub Time Machine 2,"When Lou, who has become the ""father of the In...",6.575393,...,93.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The Laws of Space and Time are About to be Vio...,Hot Tub Time Machine 2,"[{'id': 4379, 'name': 'time travel'}, {'id': 9...","[{'cast_id': 4, 'character': 'Lou', 'credit_id...","[{'credit_id': '59ac067c92514107af02c8c8', 'de...",12314651,46.5
1,2,"[{'id': 107674, 'name': 'The Princess Diaries ...",40000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,tt0368933,en,The Princess Diaries 2: Royal Engagement,Mia Thermopolis is now a college graduate and ...,8.248895,...,113.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,It can take a lifetime to find true love; she'...,The Princess Diaries 2: Royal Engagement,"[{'id': 2505, 'name': 'coronation'}, {'id': 42...","[{'cast_id': 1, 'character': 'Mia Thermopolis'...","[{'credit_id': '52fe43fe9251416c7502563d', 'de...",95149435,56.5
2,3,NaN,3300000,"[{'id': 18, 'name': 'Drama'}]",http://sonyclassics.com/whiplash/,tt2582802,en,Whiplash,"Under the direction of a ruthless instructor, ...",64.299990,...,105.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The road to greatness can take you to the edge.,Whiplash,"[{'id': 1416, 'name': 'jazz'}, {'id': 1523, 'n...","[{'cast_id': 5, 'character': 'Andrew Neimann',...","[{'credit_id': '54d5356ec3a3683ba0000039', 'de...",13092000,52.5
3,4,NaN,1200000,"[{'id': 53, 'name': 'Thriller'}, {'id': 18, 'n...",http://kahaanithefilm.com/,tt1821480,hi,Kahaani,Vidya Bagchi (Vidya Balan) arrives in Kolkata ...,3.174936,...,122.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,NaN,Kahaani,"[{'id': 10092, 'name': 'mystery'}, {'id': 1054...","[{'cast_id': 1, 'character': 'Vidya Bagchi', '...","[{'credit_id': '52fe48779251416c9108d6eb', 'de...",16000000,61.0
4,5,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",NaN,tt1380152,ko,마린보이,Marine Boy is the story of a former national s...,1.148070,...,118.0,"[{'iso_639_1': 'ko', 'name': '한국어/조선말'}]",Released,NaN,Marine Boy,NaN,"[{'cast_id': 3, 'character': 'Chun-soo', 'cred...","[{'credit_id': '52fe464b9251416c75073b43', 'de...",3923970,59.0

In [ ]:
df.columns

Index(['id', 'belongs_to_collection', 'budget', 'genres', 'homepage',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'runtime', 'spoken_languages',
       'status', 'tagline', 'title', 'Keywords', 'cast', 'crew', 'revenue',
       'half_runtime'],
      dtype='object')

In [ ]:
df['profit'] = df['revenue'] - df['budget']
df.head()

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,spoken_languages,status,tagline,title,Keywords,cast,crew,revenue,half_runtime,profit
0,1,"[{'id': 313576, 'name': 'Hot Tub Time Machine ...",14000000,"[{'id': 35, 'name': 'Comedy'}]",NaN,tt2637294,en,Hot Tub Time Machine 2,"When Lou, who has become the ""father of the In...",6.575393,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The Laws of Space and Time are About to be Vio...,Hot Tub Time Machine 2,"[{'id': 4379, 'name': 'time travel'}, {'id': 9...","[{'cast_id': 4, 'character': 'Lou', 'credit_id...","[{'credit_id': '59ac067c92514107af02c8c8', 'de...",12314651,46.5,-1685349
1,2,"[{'id': 107674, 'name': 'The Princess Diaries ...",40000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,tt0368933,en,The Princess Diaries 2: Royal Engagement,Mia Thermopolis is now a college graduate and ...,8.248895,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,It can take a lifetime to find true love; she'...,The Princess Diaries 2: Royal Engagement,"[{'id': 2505, 'name': 'coronation'}, {'id': 42...","[{'cast_id': 1, 'character': 'Mia Thermopolis'...","[{'credit_id': '52fe43fe9251416c7502563d', 'de...",95149435,56.5,55149435
2,3,NaN,3300000,"[{'id': 18, 'name': 'Drama'}]",http://sonyclassics.com/whiplash/,tt2582802,en,Whiplash,"Under the direction of a ruthless instructor, ...",64.299990,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The road to greatness can take you to the edge.,Whiplash,"[{'id': 1416, 'name': 'jazz'}, {'id': 1523, 'n...","[{'cast_id': 5, 'character': 'Andrew Neimann',...","[{'credit_id': '54d5356ec3a3683ba0000039', 'de...",13092000,52.5,9792000
3,4,NaN,1200000,"[{'id': 53, 'name': 'Thriller'}, {'id': 18, 'n...",http://kahaanithefilm.com/,tt1821480,hi,Kahaani,Vidya Bagchi (Vidya Balan) arrives in Kolkata ...,3.174936,...,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,NaN,Kahaani,"[{'id': 10092, 'name': 'mystery'}, {'id': 1054...","[{'cast_id': 1, 'character': 'Vidya Bagchi', '...","[{'credit_id': '52fe48779251416c9108d6eb', 'de...",16000000,61.0,14800000
4,5,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",NaN,tt1380152,ko,마린보이,Marine Boy is the story of a former national s...,1.148070,...,"[{'iso_639_1': 'ko', 'name': '한국어/조선말'}]",Released,NaN,Marine Boy,NaN,"[{'cast_id': 3, 'character': 'Chun-soo', 'cred...","[{'credit_id': '52fe464b9251416c75073b43', 'de...",3923970,59.0,3923970

In [ ]:
df['profit'].max()

1316249360

In [ ]:
df['profit'].min()

-107447384

In [ ]:
df['profit'].sum()

np.int64(132583553336)

In [ ]:
df['profit'].mean()

np.float64(44194517.77866667)

In [ ]:
df['profit'].median()

6121122.5

In [ ]:
df['profit'].mode()

0    0
Name: profit, dtype: int64

## **Next, we can also drop some columns which we want to drop**

In [ ]:
df.columns

Index(['id', 'belongs_to_collection', 'budget', 'genres', 'homepage',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'runtime', 'spoken_languages',
       'status', 'tagline', 'title', 'Keywords', 'cast', 'crew', 'revenue',
       'half_runtime', 'profit'],
      dtype='object')

In [ ]:
df.drop(columns=['half_runtime'],inplace=True)

In [ ]:
df['title'].head()

0                      Hot Tub Time Machine 2
1    The Princess Diaries 2: Royal Engagement
2                                    Whiplash
3                                     Kahaani
4                                  Marine Boy
Name: title, dtype: object

In [ ]:
def upper_case(column):
  return column.upper()

In [ ]:
df['upper_title'] = df['title'].apply(upper_case)
df.head()

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,spoken_languages,status,tagline,title,Keywords,cast,crew,revenue,profit,upper_title
0,1,"[{'id': 313576, 'name': 'Hot Tub Time Machine ...",14000000,"[{'id': 35, 'name': 'Comedy'}]",NaN,tt2637294,en,Hot Tub Time Machine 2,"When Lou, who has become the ""father of the In...",6.575393,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The Laws of Space and Time are About to be Vio...,Hot Tub Time Machine 2,"[{'id': 4379, 'name': 'time travel'}, {'id': 9...","[{'cast_id': 4, 'character': 'Lou', 'credit_id...","[{'credit_id': '59ac067c92514107af02c8c8', 'de...",12314651,-1685349,HOT TUB TIME MACHINE 2
1,2,"[{'id': 107674, 'name': 'The Princess Diaries ...",40000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,tt0368933,en,The Princess Diaries 2: Royal Engagement,Mia Thermopolis is now a college graduate and ...,8.248895,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,It can take a lifetime to find true love; she'...,The Princess Diaries 2: Royal Engagement,"[{'id': 2505, 'name': 'coronation'}, {'id': 42...","[{'cast_id': 1, 'character': 'Mia Thermopolis'...","[{'credit_id': '52fe43fe9251416c7502563d', 'de...",95149435,55149435,THE PRINCESS DIARIES 2: ROYAL ENGAGEMENT
2,3,NaN,3300000,"[{'id': 18, 'name': 'Drama'}]",http://sonyclassics.com/whiplash/,tt2582802,en,Whiplash,"Under the direction of a ruthless instructor, ...",64.299990,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The road to greatness can take you to the edge.,Whiplash,"[{'id': 1416, 'name': 'jazz'}, {'id': 1523, 'n...","[{'cast_id': 5, 'character': 'Andrew Neimann',...","[{'credit_id': '54d5356ec3a3683ba0000039', 'de...",13092000,9792000,WHIPLASH
3,4,NaN,1200000,"[{'id': 53, 'name': 'Thriller'}, {'id': 18, 'n...",http://kahaanithefilm.com/,tt1821480,hi,Kahaani,Vidya Bagchi (Vidya Balan) arrives in Kolkata ...,3.174936,...,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,NaN,Kahaani,"[{'id': 10092, 'name': 'mystery'}, {'id': 1054...","[{'cast_id': 1, 'character': 'Vidya Bagchi', '...","[{'credit_id': '52fe48779251416c9108d6eb', 'de...",16000000,14800000,KAHAANI
4,5,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",NaN,tt1380152,ko,마린보이,Marine Boy is the story of a former national s...,1.148070,...,"[{'iso_639_1': 'ko', 'name': '한국어/조선말'}]",Released,NaN,Marine Boy,NaN,"[{'cast_id': 3, 'character': 'Chun-soo', 'cred...","[{'credit_id': '52fe464b9251416c75073b43', 'de...",3923970,3923970,MARINE BOY

## Another way to use <code>apply()</code> involves the use of <code>lambda()</code> function.

* ### A <code>lambda()</code> function is a small anonymous function.
* ### A <code>lambda()</code> function can take any number of arguments, but can only have one expression.

In [ ]:
def add_f(x,y):
  return x+y

In [ ]:
add_f(10,20)

30

In [ ]:
x = lambda x,y:x+y

In [ ]:
x(100,200)

300

## We can also sort our dataframe by some column values in either an ascending or descending order

In [ ]:
df.sort_values(by = 'revenue',ascending = False)[['title','revenue']]

                               title     revenue
1126                    The Avengers  1519557910
1761                       Furious 7  1506249360
2770         Avengers: Age of Ultron  1405403694
684             Beauty and the Beast  1262886337
2322  Transformers: Dark of the Moon  1123746996
...                              ...         ...
695                        Tere Naam           2
1917                 The Merry Widow           1
347          The Wind in the Willows           1
1754                    Mute Witness           1
1874                         Missing           1

[3000 rows x 2 columns]

# <b>Let us explore some datetime operations and functions

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 25 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id                     3000 non-null   int64
 1   belongs_to_collection  604 non-null    object
 2   budget                 3000 non-null   int64
 3   genres                 2993 non-null   object
 4   homepage               946 non-null    object
 5   imdb_id                3000 non-null   object
 6   original_language      3000 non-null   object
 7   original_title         3000 non-null   object
 8   overview               2992 non-null   object
 9   popularity             3000 non-null   float64
 10  poster_path            2999 non-null   object
 11  production_companies   2844 non-null   object
 12  production_countries   2945 non-null   object
 13  release_date           3000 non-null   object
 14  runtime                2998 non-null   float64
 15  spoken_languages       2980 non-null   object
 16  status                 3000 non-null   object
 17  tagline                2403 non-null   object
 18  title                  3000 non-null   object
 19  Keywords               2724 non-null   object
 20  cast                   2987 non-null   object
 21  crew                   2984 non-null   object
 22  revenue                3000 non-null   int64
 23  profit                 3000 non-null   int64
 24  upper_title            3000 non-null   object
dtypes: float64(2), int64(4), object(19)
memory usage: 586.1+ KB

In [ ]:
df['release_date'][0]

'2/20/15'

In [ ]:
type(df['release_date'][0])

str

In [ ]:
df['release_date'] = pd.to_datetime(df['release_date'])

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 25 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id                     3000 non-null   int64
 1   belongs_to_collection  604 non-null    object
 2   budget                 3000 non-null   int64
 3   genres                 2993 non-null   object
 4   homepage               946 non-null    object
 5   imdb_id                3000 non-null   object
 6   original_language      3000 non-null   object
 7   original_title         3000 non-null   object
 8   overview               2992 non-null   object
 9   popularity             3000 non-null   float64
 10  poster_path            2999 non-null   object
 11  production_companies   2844 non-null   object
 12  production_countries   2945 non-null   object
 13  release_date           3000 non-null   datetime64[ns]
 14  runtime                2998 non-null   float64
 15  spoken_languages       2980 non-null   object
 16  status                 3000 non-null   object
 17  tagline                2403 non-null   object
 18  title                  3000 non-null   object
 19  Keywords               2724 non-null   object
 20  cast                   2987 non-null   object
 21  crew                   2984 non-null   object
 22  revenue                3000 non-null   int64
 23  profit                 3000 non-null   int64
 24  upper_title            3000 non-null   object
dtypes: datetime64[ns](1), float64(2), int64(4), object(18)
memory usage: 586.1+ KB

/tmp/ipykernel_434/1816763286.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['release_date'] = pd.to_datetime(df['release_date'])

In [ ]:
df['release_date'][0]

Timestamp('2015-02-20 00:00:00')

In [ ]:
df['release_date'][0].year

2015

In [ ]:
df['release_date'][0].month

2

In [ ]:
df['release_date'][0].day

20

In [ ]:
df['release_date'][0].day_name()

'Friday'

In [ ]:
df['release_date'][0].weekday()

4

In [ ]:
df['release_date'][0].hour

0

In [ ]:
df['year'] = df['release_date'].dt.year
df['month'] = df['release_date'].dt.month
df['day'] = df['release_date'].dt.day
df['day_name'] = df['release_date'].dt.day_name()
df['weekday'] = df['release_date'].dt.weekday

In [ ]:
df.head()

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,cast,crew,revenue,profit,upper_title,year,month,day,day_name,weekday
0,1,"[{'id': 313576, 'name': 'Hot Tub Time Machine ...",14000000,"[{'id': 35, 'name': 'Comedy'}]",NaN,tt2637294,en,Hot Tub Time Machine 2,"When Lou, who has become the ""father of the In...",6.575393,...,"[{'cast_id': 4, 'character': 'Lou', 'credit_id...","[{'credit_id': '59ac067c92514107af02c8c8', 'de...",12314651,-1685349,HOT TUB TIME MACHINE 2,2015,2,20,Friday,4
1,2,"[{'id': 107674, 'name': 'The Princess Diaries ...",40000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,tt0368933,en,The Princess Diaries 2: Royal Engagement,Mia Thermopolis is now a college graduate and ...,8.248895,...,"[{'cast_id': 1, 'character': 'Mia Thermopolis'...","[{'credit_id': '52fe43fe9251416c7502563d', 'de...",95149435,55149435,THE PRINCESS DIARIES 2: ROYAL ENGAGEMENT,2004,8,6,Friday,4
2,3,NaN,3300000,"[{'id': 18, 'name': 'Drama'}]",http://sonyclassics.com/whiplash/,tt2582802,en,Whiplash,"Under the direction of a ruthless instructor, ...",64.299990,...,"[{'cast_id': 5, 'character': 'Andrew Neimann',...","[{'credit_id': '54d5356ec3a3683ba0000039', 'de...",13092000,9792000,WHIPLASH,2014,10,10,Friday,4
3,4,NaN,1200000,"[{'id': 53, 'name': 'Thriller'}, {'id': 18, 'n...",http://kahaanithefilm.com/,tt1821480,hi,Kahaani,Vidya Bagchi (Vidya Balan) arrives in Kolkata ...,3.174936,...,"[{'cast_id': 1, 'character': 'Vidya Bagchi', '...","[{'credit_id': '52fe48779251416c9108d6eb', 'de...",16000000,14800000,KAHAANI,2012,3,9,Friday,4
4,5,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",NaN,tt1380152,ko,마린보이,Marine Boy is the story of a former national s...,1.148070,...,"[{'cast_id': 3, 'character': 'Chun-soo', 'cred...","[{'credit_id': '52fe464b9251416c75073b43', 'de...",3923970,3923970,MARINE BOY,2009,2,5,Thursday,3

# **Let's explore the unique and missing values**

* ### <code>unique()</code>
* ### <code>nunique()</code>
* ### <code>value_counts()</code>
* ### <code>isnull()</code>
* ### <code>fillna()</code>

In [ ]:
df['day_name'].head()

0      Friday
1      Friday
2      Friday
3      Friday
4    Thursday
Name: day_name, dtype: object

In [ ]:
df['day_name'].unique()

array(['Friday', 'Thursday', 'Wednesday', 'Sunday', 'Tuesday', 'Saturday',
       'Monday'], dtype=object)

In [ ]:
df['day_name'].nunique()

7

In [ ]:
df['day_name'].value_counts()

day_name
Friday       1332
Thursday      604
Wednesday     451
Tuesday       200
Saturday      156
Monday        138
Sunday        119
Name: count, dtype: int64

In [ ]:
df['weekday'].value_counts().sort_index()

weekday
0     138
1     200
2     451
3     604
4    1332
5     156
6     119
Name: count, dtype: int64

In [ ]:
df.isnull().sum()

id                          0
belongs_to_collection    2396
budget                      0
genres                      7
homepage                 2054
imdb_id                     0
original_language           0
original_title              0
overview                    8
popularity                  0
poster_path                 1
production_companies      156
production_countries       55
release_date                0
runtime                     2
spoken_languages           20
status                      0
tagline                   597
title                       0
Keywords                  276
cast                       13
crew                       16
revenue                     0
profit                      0
upper_title                 0
year                        0
month                       0
day                         0
day_name                    0
weekday                     0
dtype: int64

In [ ]:
df['production_countries'].isnull().sum()

np.int64(55)

In [ ]:
df.describe()

,id,budget,popularity,release_date,runtime,revenue,profit,year,month,day,weekday
count,3000.000000,3.000000e+03,3000.000000,3000,2998.000000,3.000000e+03,3.000000e+03,3000.000000,3000.000000,3000.000000,3000.000000
mean,1500.500000,2.253133e+07,8.463274,2006-10-31 08:24:57.600000,107.856571,6.672585e+07,4.419452e+07,2006.313000,6.775333,15.046333,3.245333
min,1.000000,0.000000e+00,0.000001,1976-03-31 00:00:00,0.000000,1.000000e+00,-1.074474e+08,1976.000000,1.000000,1.000000,0.000000
25%,750.750000,0.000000e+00,4.018053,1996-09-07 18:00:00,94.000000,2.379808e+06,1.795200e+04,1996.000000,4.000000,8.000000,2.000000
50%,1500.500000,8.000000e+06,7.374861,2006-07-26 12:00:00,104.000000,1.680707e+07,6.121122e+06,2006.000000,7.000000,15.000000,4.000000
75%,2250.250000,2.900000e+07,10.890983,2013-01-17 00:00:00,118.000000,6.891920e+07,4.143293e+07,2013.000000,10.000000,22.000000,4.000000
max,3000.000000,3.800000e+08,294.337037,2075-10-17 00:00:00,338.000000,1.519558e+09,1.316249e+09,2075.000000,12.000000,31.000000,6.000000
std,866.169729,3.702609e+07,12.104000,NaN,22.086434,1.375323e+08,1.123274e+08,17.237365,3.409115,8.632981,1.334318

In [ ]:
df.head()

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,cast,crew,revenue,profit,upper_title,year,month,day,day_name,weekday
0,1,"[{'id': 313576, 'name': 'Hot Tub Time Machine ...",14000000,"[{'id': 35, 'name': 'Comedy'}]",NaN,tt2637294,en,Hot Tub Time Machine 2,"When Lou, who has become the ""father of the In...",6.575393,...,"[{'cast_id': 4, 'character': 'Lou', 'credit_id...","[{'credit_id': '59ac067c92514107af02c8c8', 'de...",12314651,-1685349,HOT TUB TIME MACHINE 2,2015,2,20,Friday,4
1,2,"[{'id': 107674, 'name': 'The Princess Diaries ...",40000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,tt0368933,en,The Princess Diaries 2: Royal Engagement,Mia Thermopolis is now a college graduate and ...,8.248895,...,"[{'cast_id': 1, 'character': 'Mia Thermopolis'...","[{'credit_id': '52fe43fe9251416c7502563d', 'de...",95149435,55149435,THE PRINCESS DIARIES 2: ROYAL ENGAGEMENT,2004,8,6,Friday,4
2,3,NaN,3300000,"[{'id': 18, 'name': 'Drama'}]",http://sonyclassics.com/whiplash/,tt2582802,en,Whiplash,"Under the direction of a ruthless instructor, ...",64.299990,...,"[{'cast_id': 5, 'character': 'Andrew Neimann',...","[{'credit_id': '54d5356ec3a3683ba0000039', 'de...",13092000,9792000,WHIPLASH,2014,10,10,Friday,4
3,4,NaN,1200000,"[{'id': 53, 'name': 'Thriller'}, {'id': 18, 'n...",http://kahaanithefilm.com/,tt1821480,hi,Kahaani,Vidya Bagchi (Vidya Balan) arrives in Kolkata ...,3.174936,...,"[{'cast_id': 1, 'character': 'Vidya Bagchi', '...","[{'credit_id': '52fe48779251416c9108d6eb', 'de...",16000000,14800000,KAHAANI,2012,3,9,Friday,4
4,5,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",NaN,tt1380152,ko,마린보이,Marine Boy is the story of a former national s...,1.148070,...,"[{'cast_id': 3, 'character': 'Chun-soo', 'cred...","[{'credit_id': '52fe464b9251416c75073b43', 'de...",3923970,3923970,MARINE BOY,2009,2,5,Thursday,3

In [ ]:
df['belongs_to_collection'].fillna('not present',inplace = True)

/tmp/ipykernel_434/1206371012.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['belongs_to_collection'].fillna('not present',inplace = True)

In [ ]:
df['belongs_to_collection'].head()

0    [{'id': 313576, 'name': 'Hot Tub Time Machine ...
1    [{'id': 107674, 'name': 'The Princess Diaries ...
2                                          not present
3                                          not present
4                                          not present
Name: belongs_to_collection, dtype: object